version: '2'
services:
  app:
    container_name: syspass-app
    image: nuxsmin/docker-syspass:2.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/config
      - syspass-backup:/var/www/html/sysPass/backup
  db:
    container_name: syspass-db
    restart: always
    image: nuxsmin/docker-syspass:mysql
    ports:
      - "3306"
    environment:
      - DB_REMOTE_HOST=syspass-app.syspass_default
      - DB_REMOTE_ROOT_PASS=syspass
    volumes:
      - syspass-db:/var/lib/mysql

volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}
