version: '2'
services:
  app:
    container_name: syspass-app
    image: nuxsmin/docker-syspass:devel-php7
    restart: always
    ports:
      - "127.0.0.1:10080:80"
      - "127.0.0.1:10443:443"
    links:
      - db
    volumes:
      - /home/rdb/DEV/DOCKER/DATA/sysPass-dev/web:/var/www/html/sysPass
    environment:
      - SYSPASS_UID=1000
  db:
    container_name: syspass-db
    restart: always
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    ports:
      - "127.0.0.1:13306:3306"
    volumes:
      - syspass_db:/var/lib/mysql

volumes:
  syspass_db: {}
