version: '2'
services:
  app:
    container_name: syspass-app
    image: nuxsmin/docker-syspass:3.0-beta-php7.0
    restart: always
    ports:
      - "80"
      - "443"
    links:
      - db
    volumes:
      - /var/www/html/sysPass/config
      - /var/www/html/sysPass/backup
  db:
    container_name: syspass-db
    restart: always
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    ports:
      - "3306"
    volumes:
      - /var/lib/mysql
